exp_type: 'smnist_esn'
pixels: 28
strategy: 'replay' # replay, lwf, ewc

dataroot: '/data/cossu'
result_folder: '/data/cossu/experiments/esn/smnist_row/test_lstm_replay_25'
assess_runs: 5

use_rnn: true
rnn_units: 256

no_ray: false
max_cpus: 30
cpus_per_job: 3
cuda: true
max_gpus: 2
gpus_per_job: 0.25

### ESN
esn_units: 500
esn_layers: 1
spectral_radius: 0.99
input_scaling: 1
feedforward_layers: 1
leaky: 1

### OPTIMIZER
learning_rate: 1e-3
epochs: 10
batch_size: 128
opt_name: 'adam'

### REPLAY
mem_size: 25

# GRID SEARCH
grid:
  rnn_units:
    - 128
    - 256
  learning_rate:
    - 1e-2
    - 1e-3
