exp_type: 'smnist_esn'
pixels: 28
strategy: 'naive' # replay, lwf, ewc, cwr, naive

dataroot: '/data/cossu'
result_folder: '/data/cossu/experiments/esn/smnist_row/naive'
assess_runs: 5

no_ray: false
max_cpus: 30
cpus_per_job: 3
cuda: true
max_gpus: 2
gpus_per_job: 0.33

### ESN
esn_units: 500
esn_layers: 1
spectral_radius: 0.99
input_scaling: 1

### OPTIMIZER
learning_rate: 1e-3
epochs: 10
batch_size: 128
opt_name: 'adam'


# GRID SEARCH
grid:
  esn_units:
    - 500
    - 1000
  learning_rate:
    - 1e-2
    - 1e-3
  spectral_radius:
    - 0.99
    - 1.5
    - 0.5
  input_scaling:
    - 0.5
    - 1
    - 1.5