exp_type: 'ssc_esn'
strategy: 'replay' # replay, lwf, ewc, cwr, naive

dataroot: '/data/cossu/speech_words'
result_folder: '/data/cossu/experiments/esn/ssc/test_lstm_replay_50'
assess_runs: 5

use_rnn: true
rnn_units: 512

no_ray: false
max_cpus: 50
cpus_per_job: 3
cuda: true
max_gpus: 2
gpus_per_job: 0.25

### ESN
esn_units: 1000
esn_layers: 1
spectral_radius: 0.99
input_scaling: 1
conn_inp: 100
conn_rec: 50
feed_layers: 1
leaky: 0.2

### OPTIMIZER
learning_rate: 1e-3
epochs: 30
batch_size: 128
opt_name: 'adam'

mem_size: 50

# GRID SEARCH
grid:
  rnn_units:
    - 256
    - 512
  learning_rate:
    - 1e-2
    - 1e-3
    - 1e-4